### ISSUE TITLE
Does this work

### ISSUE THREAD

**Issue by shoya4000** [TwilightCoders/7days_os#1]
Hello there!
I'm currently attempting to find a way to run 7DTD on a Freenas server, and I've come across this code, but does it work? And if so, how does one use it?
I managed to setup MineOS using a plugin before and expected the setup to be similar, but apparently it is not?
Cheers.

**Comment by voltechs** [comment]
Hi @shoya4000, no this currently doesn't work. The idea was to leverage the linux compatibility layer, however Steam does not currently work well with this method. My recommendation (and what I'm doing) is to wait for FreeNAS 11 (formerly Corral) to stabilize and specifically 11.1 or 11.2 to come out later this year where it will support Docker. Docker will allow us to build a full native Linux image with the 7DaysToDie Server installed and it will work pretty seamlessly.

I know this doesn't get you what you want _right now_, but it's honestly worth waiting for. The process as it stands now is far too complicated and buggy to reliably host a server on FreeBSD/FreeNAS.

**Comment by shoya4000** [comment]
Roger that! Thank you sir!

**Comment by shoya4000** [comment]
Alrighty! So I'm currently working on updating to FreeNAS 11, and plan on getting right to the 7DTD server, setup.
I'm assuming that essentially what you're suggesting is to run Ubuntu in a Docker and then basically follow this walkthrough?
https://steamcommunity.com/sharedfiles/filedetails/?id=360404397

**Comment by shoya4000** [comment]
Or perhaps use this?
https://gameservermanagers.com/lgsm/sdtdserver/
